### ISSUE TITLE
Current Version Doesn't Compile

### ISSUE THREAD

**Issue by CreepyGnome** [spouliot/Andr.Unit#2]
Following instructions in the read me getting the latest from the three git repo's and using Xamarin 2.0 in Visual Studio 2010 don't compile.

MonoDroid.Dialog has this error, which then blocks all the rest since they are dependent on it.

Error   1   The type or namespace name 'DialogInterfaceButton' could not be found (are you missing a using directive or an assembly reference?) .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\RootElement.cs   380 79  MonoDroid.Dialog

The IDialogInterfaceOnClickListener method of OnClick says its supposed to be an int not a DialogInterfaceButton. So I change it to be an int and then you get these errors:

Error   8   Cannot implicitly convert type 'int' to 'Android.Text.InputTypes'. An explicit conversion exists (are you missing a cast?)  .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\EntryElement.cs  74  40  MonoDroid.Dialog
Error   9   Cannot implicitly convert type 'int' to 'Android.Text.InputTypes'. An explicit conversion exists (are you missing a cast?)  .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\EntryElement.cs  76  40  MonoDroid.Dialog
Error   10  Cannot implicitly convert type 'int' to 'Android.Text.InputTypes'. An explicit conversion exists (are you missing a cast?)  .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\EntryElement.cs  78  40  MonoDroid.Dialog
Error   2   Cannot implicitly convert type 'System.EventHandler<Android.Widget.ItemEventArgs>' to 'System.EventHandler<Android.Widget.AdapterView.ItemClickEventArgs>'  .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\DialogHelper.cs  25  37  MonoDroid.Dialog

And these warnings:

Warning 3   'Android.Widget.ItemEventArgs' is obsolete: 'Use AdapterView.ItemClickEventArgs instead'    .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\DialogHelper.cs  25  54  MonoDroid.Dialog
Warning 4   'Android.Widget.ItemEventArgs' is obsolete: 'Use AdapterView.ItemClickEventArgs instead'    .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\DialogHelper.cs  30  14  MonoDroid.Dialog
Warning 5   'Android.Widget.ItemEventArgs' is obsolete: 'Use AdapterView.ItemClickEventArgs instead'    .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\DialogHelper.cs  37  14  MonoDroid.Dialog
Warning 6   'MonoDroid.Dialog.Element.Dispose()' hides inherited member 'Java.Lang.Object.Dispose()'. Use the new keyword if hiding was intended.   .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\Element.cs   57  21  MonoDroid.Dialog
Warning 7   'MonoDroid.Dialog.Element.Dispose(bool)' hides inherited member 'Java.Lang.Object.Dispose(bool)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\Element.cs   62  32  MonoDroid.Dialog
Warning 1   'MonoDroid.Dialog.MultilineElement.Lines' hides inherited member 'MonoDroid.Dialog.EntryElement.Lines'. Use the new keyword if hiding was intended. .\GitHub\MonoDroid.Dialog\MonoDroid.Dialog\MultilineElement.cs  8   20  MonoDroid.Dialog

So I stopped there and decided to report it since it wasn't a simple fix.

**Comment by spouliot** [comment]
I have not worked on Android for quite some time. Look at the branch from pjcollins (who does QA @ Xamarin) since his fork has been maintained for the newer Xamarin.Android releases.

**Comment by CreepyGnome** [comment]
Anuj at Xamarin is touting your version as "The" versions we should be using.  I guess he isn't aware that Peter's is the current fork. I will check it out thanks.

**Comment by CreepyGnome** [comment]
Oh I looked at Greg Shackles fork which is even more forward of Peters.

https://github.com/gshackles/Andr.Unit
