### ISSUE TITLE
Support for v1.0 of NUnitLite

### ISSUE THREAD

**Issue by jamesottaway** [spouliot/Andr.Unit#5]
This library is stuck in the past of v0.6 of NUnitLite, which was released in early 2012.

The latest release of NUnitLite came late last year. I'd love to use `Andr.Unit` but it's not currently possible without pulling in a new version of NUnitLite.

**Comment by spouliot** [comment]
I do not work on XA (or use it very often) but there are other forks with more recent versions. Also recent versions of XA also ships with a runner (and a newer version of NUnitLite).
